# Generated by Django 3.2.4 on 2021-06-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de comuna')),
                ('nombreComuna', models.CharField(max_length=50, verbose_name='Nombre de la Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id')),
                ('lapublicacion', models.TextField(max_length=1000, verbose_name='lapublicacion')),
                ('fecha', models.DateField()),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EtapaUno.comuna')),
            ],
        ),
    ]
